name = "FerriteInterfaceElements"
uuid = "76cf2c14-24ca-44b2-b86c-6046d3cfcf82"
authors = ["Kim Louisa Auth <kim.auth@chalmers.se>", "Elias Börjesson <elias.borjesson@chalmers.se>", "David Rollin <d.rollin@tu-braunschweig.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
